import Providers from '@/components/providers/Providers';
import Header from '@/components/header/Header';
import '@/styles/global.scss';
import getCurrentUser from '@/utils/getCurrentUser';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const currentUser = await getCurrentUser();

  return (
    <html lang="en">
      <body>
        <main>
          <Providers>
            <Header currentUser={currentUser} />
            {children}
          </Providers>
        </main>
      </body>
    </html>
  );
}
