import Providers from '@/components/providers/Providers';
import Header from '@/components/header/Header';
import '@/styles/global.scss';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="">
        <Header />

        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
