import Providers from '@/components/providers/Providers';
import Header from '@/components/header/Header';
import '@/styles/global.scss';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <main>
          <Providers>
            {/* @ts-expect-error Server Component */}
            <Header />
            {children}
          </Providers>
        </main>
      </body>
    </html>
  );
}
